server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Blog
    username: postgres
    password: PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# TODO aşağıdkai özellikleri okuyabileceğin bir class oluştur.
application:
  registration: false
  admin-panel:
    username: admin
    password: admin

medium:
  base-url: https://api.medium.com
  user-id: 12fa9a911444035fc371fa05127ef2e5ddc8ce700345d5c58a33727fcd68c1726
  access-token: 271b87d5bfc5e8aad4518284022108130880db68d900b0435227c81d3d098dccf
